### ISSUE TITLE
レビュー

### ISSUE THREAD

**Issue by studio-rookery** [trickring/SwiftSample#1]
### let にしましょう
https://github.com/trickring/SwiftSample/blob/4c1079a129e4d21f6251e64f0d32cb978f138f63/MVVM/MVVM/ViewModels/Main/MainViewModel.swift#L14

### VC が API を叩いている
https://github.com/trickring/SwiftSample/blob/4c1079a129e4d21f6251e64f0d32cb978f138f63/MVVM/MVVM/Screens/Main/MainViewController.swift#L31-L35

VC は ViewModel にボタンが押されたということを伝えるだけで OK
実際に API を叩くのは ViewModel (or それよりモデル層に近い層)

後この書き方だと flatMap 内で Error が発生したときに Observable が終了する。
通信エラーなどがおこると、以降のボタンが反応しなくなる
https://qiita.com/t-ae/items/266a8372abf65ab1986b

### VC が表示のロジックを知っている

通信結果をもとに表示用のデータを作ってるけどそれは ViewModel の仕事

レスポンス → String?
レスポンス → UIImage?

の変換は ViewModel がやる。
VC はそれを購読するだけ。

```swift
        // メッセージ
        resultObservable
            .map{ $0?.message }
            .bind(to: resultMessageLabel.rx.text)
            .disposed(by: disposeBag)
        
        // 画像
        resultObservable
            .map{ $0?.rank }
            .bind(onNext: { rank in
                guard let rank = rank else {
                    return
                }
                switch rank {
                case 0:
                    self.resultImageView.image = #imageLiteral(resourceName: "ic_daikichi")
                case 1:
                    self.resultImageView.image = #imageLiteral(resourceName: "ic_chukichi")
                case 2:
                    self.resultImageView.image = #imageLiteral(resourceName: "ic_kichi")
                case 3:
                    self.resultImageView.image = #imageLiteral(resourceName: "ic_kyo")
                default:
                    fatalError("不正なパラメータです。(\(rank))")
                }
            })
            .disposed(by: disposeBag)
```

### 理想

```swift
        // メッセージ
        viewModel
            .message
            .bind(to: resultMessageLabel.rx.text)
            .disposed(by: disposeBag)
        
        // 画像
        viewModel
            .image
            .bind(to: resultImageView.rx.image)
            .disposed(by: disposeBag)
```

**Comment by studio-rookery** [comment]
あと UI の更新には Observable でなく Driver を使ったほうがいい。
https://qiita.com/yuzushioh/items/0a4483502c5c8569790a

**Comment by trickring** [comment]
@studio-rookery 
修正しました。確認お願いしまっす！

## ViewModel

> let にしましょう

メッセージと画像にわけて、letに修正

## ViewController

> VC が API を叩いている

VMでAPIを叩くように修正

> 後この書き方だと flatMap 内で Error が発生したときに Observable が終了する。
通信エラーなどがおこると、以降のボタンが反応しなくなる
https://qiita.com/t-ae/items/266a8372abf65ab1986b

ボタンの押下処理自体が効かなくなるということ？

> VC が表示のロジックを知っている

VMでモデルの変換ロジックを担うように修正

> あと UI の更新には Observable でなく Driver を使ったほうがいい。
https://qiita.com/yuzushioh/items/0a4483502c5c8569790a

Driverの使い所がいまいちわからなかった、、、
UIの更新ということはVCで使用しているRxSwiftの部分はすべてDriverを使用するということ？
変更しようとしたけど、Driverはbind(to: ~)ができない、、、

**Comment by trickring** [comment]
@studio-rookery 
ありがとう！修正した！
