### ISSUE TITLE
DateをStringに変換する際の注意点

### ISSUE THREAD

**Issue by trickring** [trickring/SwiftSample#6]
## 概要

* Dateを文字に変換する場合は、`yyyy/MM/dd`などのようにフォーマットを指定してしまうと、和暦表示の際におかしくなる。

## 対応

* 調査

**Comment by studio-rookery** [comment]
[【Swift】Dateの王道 【日付】](https://qiita.com/rinov/items/bff12e9ea1251e895306)
これが参考になるかも

https://qiita.com/rinov/items/bff12e9ea1251e895306
